## Math 155, Fall 2013

## Introduction to Statistical Modeling
<link rel="stylesheet" type="text/css" href="stats155.css">
```{r include=FALSE}
DL <- function(txt,i,style=c("dateNormal","dateBox","dateToday")) sprintf("<a href='Syllabus/day-by-day.html#day-%s'><span class='%s'>%s</span></a>",i,match.arg(style),txt)
```

### Day-by-Day Links

  |  |  |  |   |   |    |  |  |   |  |  |   |  |
:-----:|:-----:|:-----|:-----:|---|---|---|---|---|---|---|---|---|---|
**Sept** |  `r DL(4,1)` | `r DL(6,2)` | `r DL(9,3)` | `r DL(11,4)` | `r DL(13,5)` Q | `r DL(16,6)` | `r DL(18,7)` | `r DL(20,8)` Q |  `r DL(23,9)` | `r DL(25,10,style="dateToday")` | `r DL(27,11)` Q | `r DL(30,12)` 
**Oct** | `r DL(2,13)` | `r DL(4,14)` Q | `r DL(7,15)` | `r DL(9,16)` | `r DL(11,17)` Q | `r DL(14,18)` | `r DL(16,19)` | <a href="#" class="tooltip"><em class="dateWarning">18</em><span><strong>Mid-term Exam</strong></span></a> | `r DL(21,21)` | `r DL(23,22)` | <a href="#" class="tooltip"><em >25</em><span><strong>Fall Break!</strong></span></a> | `r DL(28,23)` | `r DL(30,24)` |
**Nov** | `r DL(1,25)` | `r DL(4,26)` | `r DL(6,27)` | `r DL(8,28)` | `r DL(11,29)` | `r DL(13,30)` | `r DL(15,31)` | `r DL(18,32)` | `r DL(20,33)` | `r DL(22,34)` | `r DL(25,35)` | `r DL(27,36)` | <a href="#" class="tooltip"><em>29</em><span><strong>Thanksgiving!</strong></span></a> | 
**Dec** | `r DL(2,37)` | `r DL(4,38)` | `r DL(6,39)` | `r DL(9,40)` |<a href="#" class="tooltip"><em class="dateWarning">11</em><span ><strong>Final exam 8am-10am. Extra Session.</strong></span></a> | <a href="#" class="tooltip"><em class="dateWarning">12</em><span ><strong>Final exam 10:30am-12:30pm. Extra Session.</strong></span></a> |   <a href="#" class="tooltip"><em class="dateWarning">16</em><span ><strong>Final exam 8am-10am. Official Time</strong></span></a> | 


Click on a date to see the syllabus/readings/assignments for that day. "Q" means quiz day.

<iframe width='600' height='300' frameborder='0' src='https://docs.google.com/spreadsheet/pub?key=0Am13enSalO74dFIyT1JTRzhSV3UtMmZ5VGRUUGtKWnc&output=html&widget=true'></iframe>

**Where's the MSCS Reading Room?** Olin-Rice 254, in the central corridor of Olin-Rice, the corridor that runs parallel to the classroom corridor and faculty office corridor.

### Resources

* **[Assignment Server](http://glimmer.rstudio.com/mosaic/Stats155/)** Your account name is the same as your Mac email prefix (e.g. ```jsmith```.  Your initial password is the last 4 digits of your student ID.  Contact the instructor to change your password.
* **Textbook**: *Statistical Modeling: A Fresh Approach* 2nd/edition.  
    Make sure to get the second edition (green cover). Available from ...
    * [Macalester Highlander Store new,used & rental](http://www.bkstr.com/webapp/wcs/stores/servlet/CourseMaterialsResultsView?catalogId=10001&categoryId=9604&storeId=286405&langId=-1&programId=3325&termId=100028623&divisionDisplayName=%20&departmentDisplayName=MATH&courseDisplayName=155&sectionDisplayName=1&demoKey=null&purpose=browse) 
    * [Amazon new & used](http://www.amazon.com/Statistical-Modeling-Approach-Second-Edition/dp/0983965870/ref=sr_1_2?ie=UTF8&qid=1376075392&sr=8-2&keywords=statistical+modeling+a+fresh+approach), 
    * [Paypal w/local author discount](Resources/book-paypal.html).
* The **RStudio Server** is [here](http://www.macalester.edu/rstudio).  Your ID is your Mac email prefix.  Your password is initialized to the last 4 digits of your student ID, e.g. ```jsmith```. [Instructions here](Resources/Starting-RStudio-Macalester.html)
* The [**EnoughR** "cheat sheet"](Resources/EnoughR/EnoughR.pdf) --- a one-sheet overview of the commands needed in the course.
* **Hand in documents**. Occasionally, your work will be in the form of a document which you will hand in by providing a link, e.g. on Google Docs or RPubs.  You hand in your link(s) [here](https://docs.google.com/a/macalester.edu/forms/d/1lTnsxkagwo4SWDg7vsfCnsTPx9x0ShIIPmz7qH7Wk_I/viewform).




