### Tyler J. Skluzacek 

# Reflection on “Sleepless Nights” by Patti Neighmond

Thinking about the sample-pool, the study in the article did a decent job of having a large enough pool – **1300 people** – in order to get results that are reflective of the actual population.   However, the article did not confirm that the 1300 people came from **different backgrounds and lifestyles**.  Due to the lack of specification, I cannot read this report through an academic lens and assume that their pool was accurately **representative of the population**.  **What if most of the pool came from coastal areas, and humidity has a large affect on dementia?**  What if 1200 of the 1300 people were actually over 90 years old?  These questions that linger post-reading make me want a more-detailed account of this study.  

All skepticism aside, I was astounded by the claim that adults with sleeping problems were **twice as likely** to develop dementia.  It’s quite difficult to argue with this statistic.  Due to my lack of statistics-education, though, I am unsure as to how sure they can be about that assumption when applying it to the population as a whole.  

............

*The* **bold** *was marked by DTK for discussion*.