# Day-36 Nov 27, 2013

## Logistic Regression and Odds

The sign of coefficients found through logistic regression is easy to interpret.  A negative coefficient means that the probability will be **lower** at that level of the categorical variable or when the quantitative value increases.  A positive coefficient means that the probability will be **higher**.

The magnitude of the coefficient is not so obvious.

Remember that in logistic regression, an ordinary linear model is being fit to the **log odds**, not the probability.

Consider a model of the probability that an applicant will be admitted to a university or college.  There are many factors that might come into play, but for simplicity, consider just two:

* The applicant's ACT score.
* Whether the applicant plays a double-reed instrument such as an oboe.


$$LogOddsOfAdmission = -2 + 0.1 ACT + 2 Oboe:Yes$$

Given an ACT score and Oboe level, you can easily compute the log odds of the applicant being admitted.  For instance, comparing two applicants with an ACT of 30 but one of whom does play the oboe and the other doesn't.

         | Oboe player | non-Oboe
---------|-------------|---------
Log odds | 1           |  3

Recall that if the probability of an outcome is $p$, then the corresponding odds are $odds = p/(1-p)$.  This formula can be inverted algebraically to give $p = odds/(1+odds)$.  You can convert the log odds to odds by exponentiation (the inverse of the logarithm).

         | non-Oboe    | Oboe player
---------|-------------|---------
Log odds | 1           |  3
Odds     | $e^1 = 2.72$ | $e^3 = 20.1$
Prob     | $2.72/3.72 = 0.73$ | $20.1/21.1 = 0.95$

Comparing the two applicants, the relative probability of admission is $0.73/0.95 = 0.77$.  That is, the non-oboe player is only 77% as likely as the oboe player to be admitted.

Another way to think about the same probabilities is to work in terms of the relative odds of being admitted.  In the example, this is $20.1/2.72 = 7.39$.  That same ratio can be found by exponentiating the difference in the log odds, i.e., $e^{3-1} = e^2 = 7.39$.  So the increase in the log odds from non-oboe to oboe gives the log odds ratio.

The log odds ratio can't be converted to a ratio of probabilities.  Odds can be converted to probabilities, but odds ratios cannot be converted to probability ratios except when the probability itself is very small.

## Case Control Study

The basic layout of data is:


Exposed    | Case   | Control  
----|--------|---------
Yes |   a    | b
No   |  c    | d


Odds ratio: $\frac{a/c}{b/d} = \frac{ad}{bc}$

### Descriptions

* George Washington Univ.: [narrative](http://www.gwumc.edu/library/tutorials/studydesign101/casecontrols.html) and some [formulas](http://www.gwumc.edu/library/tutorials/studydesign101/formulas.html#orum)

Confidence interval on the log odds ratio:
$$ \sqrt{1/a + 1/b + 1/c + 1/d}$$

Example: