## Day-by-Day Syllabus

### Math 155 

```{r include=FALSE}
require(mosaic)
# Setting up the calendar material
makeDayLinkName <- function(month,day,year=2013){
  paste("Day-", year, "-", month, "-", day, sep="")
}
dd <- function(month,day,year=2013) {
  paste("<a target='self' href='#",makeDayLinkName(month,day,year),"'>",day,"</a>",sep="")
}
days2dates <- read.csv("Days-to-Dates.csv",stringsAsFactors=FALSE)
classDayContents <- function(daynum=0,...) {
  today <- days2dates[daynum,]
  weekday <- today$Day
  month <-today$Month
  day <- today$Date
  year <- today$Year
  # put in the header and a bookmark
  paste("<hr>\n### ", 
        paste('<a name="',paste("day-",daynum,sep=""),'">',
              weekday," ", day," ", month,"</a>",sep=""))
}
todaysNotes <- function(orig,fname,marker="notes") {
  paste("<a href='../Notes/", fname, "'>",marker,"</a>","<a href='../Notes/",orig,"'>*</a>",sep="")
}
# A short form for individual problems.
PN <- function(probs,assignment="Assignment Name",prefix="Assignment" ){
  res <- ""
  for (probnum in probs){
    chap <- substr(probnum,1,nchar(probnum)-2)
    prob <- substr(probnum,nchar(chap)+1,100)
    label <- paste(chap,".",prob,sep="")
    res <- paste(res,", ",label,sep="")
  }
  return(paste(prefix," ",assignment,": ",substr(res,3,10000),sep="")) # But get rid of the trailing comma.
}

```
<link rel="stylesheet" type="text/css" href="../stats155.css">


<!--     WEEK 1  -->
`r I(classDayContents(daynum=1 ))`
**Topic**: Introduction to the course. Randomness, modeling, and inference.

**Reading**: 
* *Statistical Modeling* textbook §1.1, 1.2, 1.3.  Students on the wait list for the course may, understandably, not want to buy the book until they know they will be joining the course.  To make sure that everyone has access to the book, the publisher provides the first few chapters in online format: [Chap. 1](http://www.mosaic-web.org/go/StatisticalModeling/Chapters/Chapter-01.pdf) and [Chap. 2](http://www.mosaic-web.org/go/StatisticalModeling/Chapters/Chapter-02.pdf)
* A [recent newspaper report](http://www.nytimes.com/2012/08/21/health/how-well-you-sleep-may-hinge-on-race.html?_r=1) that frames some of the technical issues covered by the course.
* An [orientation for parents](http://rpubs.com/dtkaplan/1477).  This is the link for notes for a class the college ran for parents of entering students in 2012.  Feel free to send it to your parents or others who ask what you're going to be doing in statistics.
* Login to R via the [RStudio server](http://www.macalester.edu/rstudio). Instructions [here](../Resources/Starting-RStudio-Macalester.html). 

**Assignment**: 
* Do the reading! 

**In Class**:
* Activities on randomness.
* Basics with R.
* Using the [ScoreR assignment server](http://glimmer.rstudio.com/mosaic/Stats155/). To login, use your Mac email ID (e.g., ```bobama``` and the last 4 digits of your student ID number). Example: In-class/birthdays


**Resources**:
* A one-hour BBC documentary: [The Joy of Stats](http://www.gapminder.org/videos/the-joy-of-stats/) with Hans Rossling
* [Instructor's notes](../Notes/Day-01/Day-01-notes.html).  These are merely my plans for the class session.  Plans don't always match the actual event.  Use these for review, or to orient yourself to a missed class.  Reading these is not a substitute for class attendance.

`r I(classDayContents(daynum=2 )) # ==============================`
**Topic**: Data: cases, variables, tables, and codebooks

**Reading**: 
* Statistical Modeling §1.4, §2.1, 2.2, 2.3, 2.4
* Recent news report: [Sleep and Senility](http://www.npr.org/blogs/health/2012/08/27/159983037/sleepless-nights-may-put-the-aging-brain-at-risk-of-dementia?sc=ipad&f=1001)

**Assignment**:  
* `r I(PN(c("1RQ",101,102,104,105,110 ),assignment="One"))`
* Quick survey to do **before** class: [link](https://docs.google.com/spreadsheet/viewform?hl=en&formkey=dEV1cW1rTWhpLUhITVFNVGpnQjNqT3c6MQ#gid=0).  We'll use these data in class.

**In-class**: 

* Student introductions at [this link](http://www.mosaic-web.org/go/firepad/examples/teamedit.html?project=Math155&doc=Intros).
* Starting with R. 
* Hand in a link to your [group spreadsheet](https://docs.google.com/a/macalester.edu/forms/d/1lTnsxkagwo4SWDg7vsfCnsTPx9x0ShIIPmz7qH7Wk_I/viewform).  You'll use the same process to hand in your elevator experiment spreadsheet on Monday.

**Resources**:
* [Instructor's notes](../Notes/Day-02/Day-02-notes.html)
 



`r I(classDayContents(daynum=3 ))`
**Topic**: Organization of data (cont.), descriptive statistics

**Reading**: 
* SM §2.5, SM §3.1, 3.2, 3.3
* [XKCD cartoon](http://xkcd.com/539/)

**Assignment**:
* `r I(PN(c(111,112,"2RQ",202,204,301,323,353),assignment="Two"))`
* Elevator experiment: [Instructions](../In-Class-Activities/elevator.html). -- Enter a link to your Google Spreadsheet file (and other files as needed) [here](https://docs.google.com/a/macalester.edu/forms/d/1lTnsxkagwo4SWDg7vsfCnsTPx9x0ShIIPmz7qH7Wk_I/viewform).




Still under construction ...    
* Not ready yet.  Wait until this note is removed ... [Start-of-course knowledge survey FIX THIS LINK](https://dl.dropbox.com/u/5098197/Exercises/HTML/SM2-Statistics-Knowledge-Survey/SM2-Statistics-Knowledge-Survey-A.html?access=ISMf12) 


**In-Class**:
* Table on [Marital status of active-duty forces](https://dl.dropbox.com/u/5098197/Math155/ActiveDuty_MaritalStatus.xls) from [data.gov](https://explore.data.gov/Population/Active-Duty-Marital-Status/r84k-m39h) and the [PDF handout](https://dl.dropbox.com/u/5098197/ISM/How-Many-Variables.pdf).  Hand in your sample data file [here](https://docs.google.com/a/macalester.edu/forms/d/1lTnsxkagwo4SWDg7vsfCnsTPx9x0ShIIPmz7qH7Wk_I/viewform).   

**Resources**:
* [Instructor's notes](../Notes/Day-03/Day-03-notes.html) 


<!--     WEEK 2 -->

`r I(classDayContents(daynum=4 ))`
**Topic**: Descriptive statistics: variance

**Reading**: SM §3.4, 3.5, [XKCD cartoon](http://xkcd.com/833/)

**Assignment**: `r I(PN(c(209,214,222,302,303,304,305,306,308,311,312,315,317,318,319 ),assignment="Three"))`

**In Class**: 
* Starting R with Graphics. [PDF handout](../In-Class-Activities/StartRwithGraphics/R-stats-intro.pdf) and [Rmd template for your report](https://raw.github.com/dtkaplan/Stats155/gh-pages/Notes/Day-04/StartRwithGraphics-template.Rmd)
* [Measures of a distribution](https://dl.dropbox.com/u/5098197/ISM/Numerical-Summaries.pdf)

**Resources**: 
* [Instructor's notes](../Notes/Day-04/Day-04-notes.html)
* A *RadioLab* [episode about stochasticity](http://www.radiolab.org/2009/jun/15/)



<!-- r I(todaysNotes("2012-09-12.html", "2013-02-06.html", "notes")) --> 

`r I(classDayContents(daynum=5 ))`
**Topic**: Groupwise Models

**Reading**: SM Ch. 4

**Assignment**: `r I(PN(c(314,316,"3RQ",403,404,405,406,410),assignment="Four"))`

**In Class**:

* Weekly Quiz.  This week, it's about R. A [study-guide is available here](https://dl.dropboxusercontent.com/u/5098197/Stat155Fall2013/ThingsWithHints/Quiz-1-R-Study-Guide.html).

**Resources**:
* [Instructor's notes](../Notes/Day-05/Day-05-notes.html)

<!-- Notes: `r I(todaysNotes("2012-09-14.html", "i"))` -->
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-09-14-class) -->

`r I(classDayContents( daynum=6 ))`
**Topic**: Model values, residuals, and variance.  Sampling and resampling.

**Reading**: SM Ch. 4 (review).  SM §5.1, 5.2

**Assignment**: `r I(PN(c(354,"4RQ",407,408,501,502),assignment="Five"))`

<!-- **Notes**:  I(todaysNotes("2012-09-17.html", "i")) -->
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2013-02-08-class) -->

**In-Class**: 
* Modeling wages with groupwise means

**Resources**:
* [Instructor's notes](../Notes/Day-06/Day-06-notes.html)
* [Unfit models](https://dl.dropbox.com/u/5098197/ISM/Unfit-Models.pdf) activity

<!--      WEEK 3      -->


`r I(classDayContents( daynum=7 ))`
**Topic**: Confidence intervals

**Reading**: SM §5.3, 5.4, 5.5, 5.7

**Assignment**: `r I(PN(c("5RQ",503,512,517,520),assignment="Six"))`

**In Class**:  
* Precision and sampling.  (Precision is easy.  Accuracy will take the rest of the course!)
* Estimation in *[Breaking Bad](https://www.dropbox.com/s/o1n1hh6njh1mqdf/money-estimation.html)*

**Notes**: 
* [Instructor's notes](../Notes/Day-07/Day-07-notes.html)

<!-- `r I(todaysNotes("2012-09-19.html", "i"))` --> 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2013-02-11-class) -->


`r I(classDayContents( daynum=8 ))`
**Topic**: Language of Models

**Reading**: SM §6.1, 6.2, 6.3, 6.4

**Assignment**: 
* Required: `r I(PN(c(513,523, 530, 531,601,602,604,611,613),assignment="Seven"))`
* Optional, for the theoretically oriented.  `r I(PN(c(540),assignment="Seven-Opt"))`

**In Class**:
Weekly Quiz

**Resources:**: 
* [Instructor's notes](../Notes/Day-08/Day-08-notes.html)
* Bias in sampling: Steven Strogatz on [why your friends have more friends than you do](http://opinionator.blogs.nytimes.com/2012/09/17/friends-you-can-count-on/?ref=opinion)
* One of our data sets is based on the General Social Survey from 1985.  Here's an article based on the ongoing [General Social Survey in 2012](http://www.nytimes.com/2012/09/21/health/intangible-dividend-in-an-anti-poverty-experiment-happiness.html?_r=1&hp).

<!-- `r I(todaysNotes("2012-09-21.html", "i"))` -->
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2013-02-13-class) -->

`r I(classDayContents( daynum=9 ))`
**Topic**: From Model Terms to Formulas and Coefficients

**Reading**: SM §6.5, 6.6, 6.7, SM §7.1, 7.2

**Assignment**: 
* Required `r I(PN(c("6RQ",605,610, 612, 701, 702 ),assignment="Eight"))`
* Optional
    * `r I(PN(c(620,621),assignment="Eight-Opt"))` 
    * [XKCD cartoon](http://xkcd.com/418/).  What regression model for this?

**In Class**: 
* Partitioning variability.  
* [Selecting Model Terms](https://dl.dropbox.com/u/5098197/ISM/Select-Terms-Activity.pdf)

**Notes**: `r I(todaysNotes("2012-09-24.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2013-02-15-class) -->


<!--     WEEK 4     -->

`r I(classDayContents( daynum=10 ))`
**Topic**: Formulas and Coefficients

**Reading**: 
* SM §7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9
* [XKCD cartoon](http://xkcd.com/605/)

**Assignment**: 
* Exercises `r I(PN(c("7RQ", 704, 705,710,711,712, 713,715),assignment="Nine"))`
* Car project (group project): `r I(PN(c(723)))` 
* [Instructions for reading Google spreadsheets into R](http://rpubs.com/dtkaplan/GoogleSpreadsheets)
* Using the R-Markdown system. LINK TO HANDIN SITE FOR SPREADSHEETS and REPORTS

**In Class**:
* [Untangling House Prices](https://dl.dropbox.com/u/5098197/ISM/UntanglingHousePrices.pdf)

**Notes**: 

<!-- `r I(todaysNotes("2012-09-26.html", "i"))`  -->
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2013-02-18-class) -->


`r I(classDayContents( daynum=11 ))`
**Topic**: Fitting and Least Squares

**Reading**: SM §7.10, SM §8.1, 8.2 

**Assignment**: `r I(PN(c(714,716,721,722, 731, 801),assignment="Ten"))`

**In Class**: Weekly Quiz

**Notes**: `r I(todaysNotes("2012-09-28.html", "i"))`  
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2013-02-20-class)  -->


`r I(classDayContents( daynum=12 ))`
**Topic**: Geometry of Least Squares Fitting

**Reading**: SM §8.3

**Assignment**: `r I(PN(c(802, 804, 805, 811),assignment="Eleven"))`

**In Class**: 
* [Case versus Variable Spaces](https://dl.dropbox.com/u/5098197/ISM/case-vs-variable-space.pdf)

**Notes**: `r I(todaysNotes("2012-10-01.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-02-22-class) -->

<!--     WEEK 5   -->

`r I(classDayContents( daynum=13 ))`
**Topic**: Redundancy and Colinearity

**Reading**: SM §8.4, 8.5

**Assignment**:  `r I(PN(c("8RQ",805,812),assignment="Twelve"))`

**In Class**: [Redundancy activity](https://dl.dropbox.com/u/5098197/ISM/redundancy.pdf) 

**Notes**: `r I(todaysNotes("2012-10-03.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-10-03-class) -->

`r I(classDayContents( daynum=14 ))`
**Topic**: Correlation and Partitioning, $R^2$

**Reading**: SM Ch. 9

**Assignment**: `r I(PN(c(901,902,904,905),assignment="Thirteen"))`

**In Class**: Weekly Quiz

**Notes**: `r I(todaysNotes("2012-10-05.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-10-05-class) -->

`r I(classDayContents( daynum=15 ))`
**Topic**: Correlation and Partitioning (continued)

**Reading**: SM Ch. 9 (review)

**Assignment**: `r I(PN(c("9RQ",910,911,912,913,921),assignment="Fourteen"))`

**Notes**: `r I(todaysNotes("2012-10-08.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-10-08-class) -->

<!--      WEEK 6 -->


`r I(classDayContents( daynum=16 ))`
**Topic**: Total and Partial Relationships

**Reading**: SM Ch. 10

**Assignment**: `r I(PN(c(922, 923,1001,1004,1010),assignment="Fifteen"))`

**In Class**: 

* [Total versus Partial](https://dl.dropbox.com/u/5098197/ISM/total-partial.pdf)
* Form groups for the [**term project**](http://rpubs.com/dtkaplan/math155-spring2013-term-project).  Enter information about your project and group [on this Google Doc](https://docs.google.com/a/macalester.edu/document/d/12dyhb_FUFWqbagUVGFLWsvLnNLy9jW2umiPiKUjZ4Kc/edit?usp=sharing) so that the whole class can see.  **Also**, to get a grade, **every person** should enter the names etc. [here on Moodle](https://moodle.macalester.edu/mod/assign/view.php?id=19817)

**Notes**: `r I(todaysNotes("2012-10-10.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-10-10-class) -->

**On Your Own**: [Is coffee good for you?](http://well.blogs.nytimes.com/2012/05/16/coffee-drinkers-may-live-longer/?ref=health)

`r I(classDayContents( daynum=17 ))`
**Topic**: Total and Partial Relationships (continued)

**Reading**: SM Ch. 10 (review)

**Assignment**: `r I(PN(c("10RQ",1005,1011,1012,1020),assignment="Sixteen"))`

**In Class**: Weekly Quiz

**Notes**: `r I(todaysNotes("2012-10-12.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-10-12-class) -->

`r I(classDayContents( daynum=18 ))`
**Topic**: Confidence Intervals on Coefficients

**Reading**: SM Ch. 12

**Assignment**: `r I(PN(c(1021,1201,1202,1204,1205),assignment="Seventeen"))`

**Notes**: `r I(todaysNotes("2012-10-15.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-10-15-class) -->

<!--     WEEK 7   -->

`r I(classDayContents( daynum=19 ))`
**Topic**: Review for Exam

**Reading**:

**Assignment**: [Review Problems](https://dl.dropbox.com/u/5098197/ISM/Mid-Term-Review.pdf) 

**Notes**: `r I(todaysNotes("2012-10-17.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-10-17-class) -->


`r I(classDayContents( daynum=20 ))`
**Mid-term Exam**

Review Problems: [without answers](https://dl.dropbox.com/u/5098197/ISM/Mid-Term-Review.pdf) and then again, [with answers](https://dl.dropbox.com/u/5098197/ISM/Mid-Term-Review-answers.pdf)

**[Exam Answers and Grading Rubric] to be posted.** 
<!--(http://rpubs.com/dtkaplan/2243) --> 

`r I(classDayContents( daynum=21 ))`
**Topic**: Probability Models

**Reading**: SM Ch. 11

**Assignment**: `r I(PN(c("11RQ",1101,1102,1104,1105,1110,1121,1122),assignment="Eighteen"))`

**Notes**: `r I(todaysNotes("2012-10-24.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-10-24-class) -->



<!--    WEEK 8 -->

`r I(classDayContents(daynum=22))`
**Topic** Continuous Random Variables.  Confidence Intervals on Coefficients.

**Reading**: Review SM Ch. 11.  Start on SM Ch. 12

**Assignment**: 
* `r I(PN(c(1111,1130,1135,1137),assignment="Nineteen"))`


`r I(classDayContents( daynum=23 ))`
**Topic**: Confidence Intervals on Coefficients (continued)

**Reading**: SM Ch. 12

**Assignment**: `r I(PN(c("12RQ",1210,1212),assignment="Twenty"))`

**In Class**:
* Kaplan's section: Sign up for meeting to review your term project ideas.  [Sign-up sheet](https://docs.google.com/spreadsheet/ccc?key=0Am13enSalO74dFJJNFBNNEt5b1hnVVp4bGhIa2VPRVE&usp=sharing)

**Notes**: `r I(todaysNotes("2012-10-22.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-10-22-class) -->


`r I(classDayContents( daynum=24 ))`
**Topic**: Hypothesis Testing

**Reading**: SM Ch. 13

**Assignment**: `r I(PN(c(1301),assignment="Twenty-one"))`

**Notes**: `r I(todaysNotes("2012-10-29.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-10-29-class) -->

<!--     WEEK 9    -->



`r I(classDayContents( daynum=25 ))`
**Topic**: Hypothesis Testing (continued)

**Reading**: Review SM Ch. 13

**Assignment**: 
* `r I(PN(c("13RQ",1302),assignment="Twenty-two"))`
* Discuss your draft [Survey Project](https://dl.dropbox.com/u/5098197/ISM/survey-project.pdf) with your instructor. 

**In Class**: `r I(PN(c(1315)))`

**On Your Own**: An [introduction to Bayes Theorem](http://lesswrong.com/lw/2b0/bayes_theorem_illustrated_my_way/)

**Notes**: `r I(todaysNotes("2012-10-31.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-10-31-class) -->

**On Your Own**: The paper that won the [2012 Ignobel prize](http://www.improbable.com/ig/winners/) in neuroscience: [On brain activity in a dead salmon](http://www.jsur.org/ar/jsur_ben102010.pdf)

`r I(classDayContents( daynum=26 ))`
**Topic**: Testing Whole Models with $latex R^2$ and F

**Reading**: SM §14.1, 14.2, 14.3, 14.5

**Assignment**: `r I(PN(c(1401,1402),assignment="Twenty-three"))`

**In Class**: 
* `r I(PN(c(1422)))`

**Notes**: `r I(todaysNotes("2012-11-02.html", "i"))`  
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-11-02-class) -->

`r I(classDayContents( daynum=27 ))`
**Topic**: Interpreting the p-value

**Reading**: 
* SM §14.4
* [XKCD cartoon](http://xkcd.com/882/) and [another](http://xkcd.com/628/) and [yet another](http://xkcd.com/892/)

**Assignment**: `r I(PN(c("14RQ",1404,1405,1411,1412,1424),assignment="Twenty-four"))`

**In Class**: `r I(PN(c(1421)))`

**Notes**: `r I(todaysNotes("2012-11-05.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-11-05-class) -->

**On Your Own**: [Journalistic deficit disorder](http://www.economist.com/node/21563275)

<!--    WEEK   10 -->

`r I(classDayContents( daynum=28 ))`
**Topic**: Hypothesis Testing on Parts of Models

**Reading**: SM Ch. 15

**Assignment**: `r I(PN(c("15RQ",1501),assignment="Twenty-five"))`

**In Class**: [Evaluating your election result model](http://glimmer.rstudio.com/mosaic/Election2012/)

**Notes**: `r I(todaysNotes("2012-11-07.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-11-07-class) -->

**On Your Own**: [Dance of the p-values](https://www.youtube.com/watch?v=ez4DgdurRPg)

`r I(classDayContents( daynum=29 ))`
**Topic**: Hypothesis Testing on Parts of Models (continued)

**Reading**: SM Ch. 15 (review)

**Assignment**: `r I(PN(c(1502,1504,1505,1511),assignment="Twenty-six"))`

**Notes**: `r I(todaysNotes("2012-11-09.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-11-09-class) -->

**On Your Own**: [What is a p-value?](https://www.youtube.com/watch?v=ax0tDcFkPic&feature=related)


`r I(classDayContents( daynum=30 ))`
**Topic**: Choosing model terms

**Reading**: [XKCD cartoon](http://xkcd.com/675/)

**Assignment**:  `r I(PN(c(1512,1521),assignment="Twenty-seven"))`

**Notes**: `r I(todaysNotes("2012-11-12.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-11-12-class) -->

<!--     WEEK 11    -->

`r I(classDayContents( daynum=31 ))`
**Topic**: Non parametrics

**Reading**: [XKCD cartoon on frequentist vs Bayesian](http://xkcd.com/1132/)

**Assignment**: 
*`r I(PN(c(1522),,assignment="Twenty-eight"))`
* Get final approval for your [survey project](https://dl.dropbox.com/u/5098197/ISM/survey-project.pdf) from your instructor.

**Notes**: `r I(todaysNotes("2012-11-14.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-11-14-class) -->

-----------------
### Toward the End of the Semester

You've now seen the core concepts and methods of statistical modeling.  The rest of the semester is intended to help you review and solidify your understanding.  We'll do this by using statistical models in three contexts:

1. Yes/No models --- logistic regression.  The aims here are to provide you with an important technique that employs the logic of statistical modeling but with a slightly different nomenclature.
2. Causation and the choice of covariates.  You've seen how to choose model terms based on ideas from statistical inference and "evidence."  Now you'll see a new criterion for selecting model terms that respects what you believe is true about causation.
3. Experiment.  The basic idea is to impose an intervention on a system and then analyzing the results.  Experiments provide the most compelling form of evidence, yet they cannot always (or even often) be performed.  


This is a good time to start to review.  As we explore these new contexts, do the exercises from Chapter 15 to solidify your understanding of that basic material.  These exercises will be due at the last class day.


`r I(classDayContents( daynum=32 ))`
**Topic**: Logistic regression

**Reading**: SM Ch. 16

**Assignment**: `r I(PN(c(),assignment="Twenty-nine"))` BLANK FOR NOW

**In Class**: Modeling Barry Bonds

**Notes**: `r I(todaysNotes("2012-11-16.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-11-16-class) -->



`r I(classDayContents( daynum=33 ))`
**Topic**: Odds Ratios and Logistic regression

**Reading**: SM Ch. 16

**In Class**: [Power and deer crossings](http://rpubs.com/dtkaplan/deer-crossing)

**Notes**: `r I(todaysNotes("2012-11-19.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-11-19-class) -->


<!--    WEEK 12  -->

`r I(classDayContents( daynum=34 ))`
**Topic**: Power and the Alternative Hypothesis

**In Class**: 
* [Deer crossing](http://rpubs.com/dtkaplan/deer-crossing) ... continued

* The **last weekly quiz**

**Notes**: `r I(todaysNotes("2012-11-21.html", "i"))` 
<!--  [Class notes](http://rpubs.com/dtkaplan/m155-2012-11-21-class) -->

`r I(classDayContents( daynum=35 ))`
**Topic**: Power. Logistic Regression.

**Reading**: 
* SM Ch. 16

**In Class**:
* [Processing Survey Data](http://rpubs.com/dtkaplan/m155-processing-survey-data) and the template itself: [cut and paste from here](https://raw.github.com/dtkaplan/Statistical-Modeling-A-Fresh-Approach/gh-pages/Activities/SurveyProcessing.Rmd)

**Assignment**: 
* `r I(PN(c("16RQ",1601,1602,1604),assignment="Thirty"))`


**On Your Own**:
* [Why most published research findings are false](http://www.plosmedicine.org/article/info:doi/10.1371/journal.pmed.0020124)
* [Advice on choosing a major](http://xkcd.com/1052/) to the tune of "A Modern Major General." [Listen here](http://www.youtube.com/watch?v=pRexBMPeRTo). See also the original from [The Pirates of Penzance](http://www.youtube.com/watch?v=zSGWoXDFM64), an [elemental version](http://www.youtube.com/watch?v=AcS3NOQnsQM), and, without endorsement, [a collection](http://www.youtube.com/playlist?list=PL81E47F8C9314A1D7)

**Notes**: `r I(todaysNotes("2012-11-26.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-11-26-class) -->



`r I(classDayContents( daynum=36 ))`
**Topic**: Causation

**Reading**: 
* SM Ch. 17
* [XKCD cartoon](http://xkcd.com/925/)

**Assignment**: `r I(PN(c(1605,1610,1612),assignment="Thirty-one"))`

**In-Class**:
* [Hypothetical Causal Networks](../../Activities/ConstructingHypotheticalNetworks.html)
* [The Power of Vitamin D](https://dl.dropbox.com/u/5098197/ISM/power-vitamin-D.pdf)

**Notes**: `r I(todaysNotes("2012-11-29.html", "i"))` 

<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-11-28-class) -->


<!-- WEEK 13   -->

`r I(classDayContents( daynum=37 ))`
**Topic**: Causation

**Reading**: 
* SM Ch. 17
* [XKCD cartoon](http://xkcd.com/552/)

**In Class**:
* Writing up your survey report in R. [Notes](http://rpubs.com/dtkaplan/5866).  You will want to copy the [raw template from here](https://raw.github.com/dtkaplan/Statistical-Modeling-A-Fresh-Approach/gh-pages/Activities/SurveyReport.Rmd) to cut and paste into RStudio.

**Assignment**: `r I(PN(c("17RQ",1701,1702,1705),assignment="Thirty-two"))`



`r I(classDayContents( daynum=38 ))`
**Topic**: Causation

**Reading**: SM Ch. 17 and [XKCD cartoon](http://xkcd.com/687/)

**Assignment**: `r I(PN(c(1706,1707,1708,1710),assignment="Thirty-three"))`


`r I(classDayContents( daynum=39 ))`
**Topic**: Experiment and Design

**Reading**: SM Ch. 18

**Notes**: `r I(todaysNotes("2012-12-05.html", "i"))` 
<!-- [Class notes](http://rpubs.com/dtkaplan/m155-2012-12-05-class) -->


### Final Exam

* [Review Materials](http://rpubs.com/dtkaplan/5792)
